// Generated by Wrangler on Wed Jun 05 2024 01:16:01 GMT-0500 (Central Daylight Time)
// by running `wrangler types`

interface Env {
	FEEDBIN_EMAIL: string;
	FEEDBIN_PASSWORD: string;
	API_TOKEN: string;
	DB: D1Database;
}
