// Generated by Wrangler by running `wrangler types`

interface Env {
	KV_API_CACHE: KVNamespace;
	FEEDBIN_EMAIL: string;
	FEEDBIN_PASSWORD: string;
	API_TOKEN: string;
	BSKY_LOGIN: string;
	BSKY_PASSWORD: string;
	DB: D1Database;
}
