// Generated by Wrangler on Sat Jun 08 2024 15:15:18 GMT-0500 (Central Daylight Time)
// by running `wrangler types`

interface Env {
	KV_API_CACHE: KVNamespace;
	FEEDBIN_EMAIL: string;
	FEEDBIN_PASSWORD: string;
	API_TOKEN: string;
	DB: D1Database;
}
