node_compat = true

[[d1_databases]]
binding = "DB"                                       # i.e. available in your Worker on env.DB
database_name = "kevinkipp.com"
database_id = "d5c17b3d-78fb-4894-a743-95b19cac53a9"
preview_database_id = "DB"

[[kv_namespaces]]
binding = "KV_API_CACHE"
id = "8f88c02d5415430f8e4a751021268b43"

[env.preview]
name = "preview"

[[env.preview.d1_databases]]
binding = "DB"                                       # i.e. available in your Worker on env.DB
database_name = "kevinkipp.com_preview"
database_id = "167258f1-9e95-4b98-80fd-df0f4e81112b"
